### ISSUE TITLE
db 게시글 테이블 피드백

### ISSUE THREAD

**Issue by hjhello423** [hjdeepsleep/D2-clone-backend#1]
게시글 테이블 

아래에서 [테이블-컬럼명] 형식으로 작성

---

1. id 컬럼 타입은 **bigint**가 좋음
1. id 컬럼명은 **테이블이름_id** 의 형식이 좋아보임
1. 모든 컬럼 이름은 **소문자**와 '**_**'의 조합으로 가는게 어떤지?
1. [d2_post-image]는 게시물 하나에 여러개의 이미지가 들어가니까 테이블 새로 만들고 참조하는게 맞을꺼 같은데? ( [d2_post-tags] 이것도, [d2_image] 테이블 생성함 )
1. [d2_post-authors] 이건 어디서 사용?
1. [d2_post-socialurl] 이것도 게시글의 id값만 api로 전달하기 때문에 뷰에서 처리해야할 부분 같음, DB에서 관리 필요 없을듯. 사용 한다면 socialurl -> social_url으로 변경
1. [링크](https://d2.naver.com/helloworld/1329) 에서 '본문내용'과 '댓글' 사이에 있는 '관련글' 항목 서버에서 제공 필요 해보임(DB저장 필요는 없겠다)

**Comment by ess234** [comment]
구두로 정리한 수정 사항 1, 2, 3, 6번 처리 완료
